# Generated by Django 5.2 on 2025-06-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='phone',
        ),
    ]
