# Generated by Django 5.1.6 on 2025-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=20, verbose_name='Ad Platform')),
                ('inquiry_date', models.DateTimeField(auto_now_add=True, verbose_name='Inquiry Date')),
                ('booking_status', models.CharField(choices=[('booked', 'Booked Appointment'), ('not_booked', 'Did Not Book'), ('follow_up', 'Needs Follow Up')], max_length=20, verbose_name='Booking Status')),
                ('reason', models.CharField(blank=True, choices=[('price', 'Price Concerns'), ('location', 'Location Not Convenient'), ('timing', 'Timing Not Suitable'), ('other_doctor', 'Preferred Another Doctor'), ('other', 'Other Reason')], max_length=20, null=True, verbose_name='Reason for Not Booking')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
